scripts/licscantool: Add missing argument formatter
Fixes

  print('%s' % (row_lbl, ''.join(json_data[pn]['packageInformation']['LICENSE:' + pkg])))
        ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  TypeError: not all arguments converted during string formatting

Signed-off-by: Niko Mauno <niko.mauno@vaisala.com>